# Generated by Django 4.2.20 on 2025-04-18 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="authors/")),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="description",
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, upload_to="books/"),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="reviews",
            field=models.IntegerField(default=2700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="main.author",
            ),
        ),
    ]
