# Generated by Django 4.2.20 on 2025-04-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_book_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="ebook",
            field=models.FileField(default="", upload_to="documents/pdfs/"),
            preserve_default=False,
        ),
    ]
